# Generated by Django 6.0.1 on 2026-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='itens/')),
                ('autor', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
